### ISSUE TITLE
Badges cache too long?

### ISSUE THREAD

**Issue by rmcgibbo** [Binstar/binstar#125]
Latest binstar release of this package is `1.2.0`, uploaded about a month ago, but the badge shows `1.1.0`. I'm not sure if this is because I'm doing something wrong, or perhaps the CDN is really aggressively caching the svg?

- https://binstar.org/omnia/mdtraj/
- https://binstar.org/omnia/mdtraj/badges/version.svg

**Comment by srossross** [comment]
@rmcgibbo ,Yes I think there is a cacheing issue. I am going to look into this as soon as possible.

**Comment by rmcgibbo** [comment]
it looks like this has been fixed.
