### ISSUE TITLE
binstar mismatching platforms on upload

### ISSUE THREAD

**Issue by jiffyclub** [Binstar/binstar#150]
I made a package with conda on my Mac then used `conda convert -p all osx-64/zbox-1.2.0-py34_0.tar.bz2` to broadcast it to all platforms. When I try to use the binstar CLI to upload the files it seems to be very confused. I tell it to upload the linux-32 package and it says it's uploading the osx-64 package:

```
> binstar upload linux-32/zbox-1.2.0-py34_0.tar.bz2
Using binstar api site https://api.binstar.org
detecting package type ...
conda
extracting package attributes for upload ...
done

Uploading file jiffyclub/zbox/1.2.0/osx-64/zbox-1.2.0-py34_0.tar.bz2 ...
 uploaded 6 of 6Kb: 100.00% ETA: 0.0 minutes


Upload(s) Complete

Package located at:
https://binstar.org/jiffyclub/zbox
```

When I go to https://binstar.org/jiffyclub/zbox the badge indicates there is a linux-32 version, but when I go to https://binstar.org/jiffyclub/zbox/files it only shows an osx-64 version.

```
> binstar --version
binstar Command line client (version 0.10.3)
```

```
> conda info
Current conda install:

             platform : osx-64
        conda version : 3.10.1
  conda-build version : 1.12.0
       python version : 3.4.3.final.0
     requests version : 2.6.0
     root environment : /Users/matt/miniconda3  (writable)
  default environment : /Users/matt/miniconda3
     envs directories : /Users/matt/miniconda3/envs
        package cache : /Users/matt/miniconda3/pkgs
         channel URLs : https://conda.binstar.org/t/<TOKEN>/synthicity/osx-64/
                        https://conda.binstar.org/t/<TOKEN>/synthicity/noarch/
                        https://repo.continuum.io/pkgs/free/osx-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/osx-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : /Users/matt/.condarc
    is foreign system : False
```

**Comment by jiffyclub** [comment]
Just confirmed this on another computer. I'm completely blocked from uploading to binstar.org.

**Comment by asmeurer** [comment]
Can you unarchive the converted package and verify that the platform is correct in `info/index.json`?

**Comment by jiffyclub** [comment]
The platform is correct, but the subdir is wrong?

```json
> cat linux-32/zbox-1.2.0-py27_0/info/index.json | jq .
{
  "name": "zbox",
  "version": "1.2.0",
  "build_number": 0,
  "depends": [
    "cytoolz >=0.7.0",
    "python 2.7*"
  ],
  "arch": "x86",
  "platform": "linux",
  "license": "ISC License (ISCL)",
  "subdir": "osx-64",
  "build": "py27_0"
}
```

**Comment by chrisnatali** [comment]
FYI, confirmed this issue using same conda/binstar versions on linux-64 platform.  Corrected the subdir attribute in the converted info/index.json for the appropriate platform (osx-64 in my case) and at least it uploaded to binstar.  Awaiting testing whether the install on that platform works.

**Comment by jiffyclub** [comment]
So is the official recommendation right now that if you want to upload converted packages to Binstar you need to manually fix the "subdir" field in each converted package?

**Comment by kpurdon** [comment]
Not sure this is complete solution but I was able to get around this error by downgrading binstar `conda install binstar=0.10.1`.

**Comment by damianavila** [comment]
We experienced the same with the automatic bokeh builds...

**Comment by jiffyclub** [comment]
Sorry to be a bother, but has there been any progress on this?

**Comment by asmeurer** [comment]
The problem should be fixed in the latest version of conda-build.

**Comment by jiffyclub** [comment]
Confirmed this seems to be fixed. Thanks.
